import requests


WS_IP = '192.168.8.101'
WS_PORT = 25000
WMF_BASE_URL = 'https://wmf24.ru'
WMF_DATA_URL = "https://wmf24.ru/api/errorhook"
WS_URL = f'ws://{WS_IP}:{WS_PORT}/'
DB_PATH = '/root/wmf_1100_1500_5000_router/wmf.db'
#DB_PATH = 'wmf.db'
ERROR_COLLECTOR_INTERVAL_SECONDS = 5
CHECK_MACHINE_STATUS_INTERNAL = 1 * 60
REQUEST_TIMEOUT = 5
DEFAULT_WMF_PARAMS = 'cocoa=99&coffee=99&milk=99&water=99&draining=0'
LOGGER_TEXT_LIMIT = 512
WEBSOCKET_CONNECT_TIMEOUT = 5
TELEGRAM_REPORT_INTERVAL_MINUTES = 24 * 60
TELEGRAM_REPORT_RECORDS_TO_KEEP = 30
CLEAN_DB_DAYS = 30
REQUEST_RETRIES = 5

